"""
Multi-horizon congestion forecast for events.

Produces risk estimates at standard operational horizons:
  T-2h, T-1h, T-30m, Event Start, T+1h, T+2h, T+3h, T+4h (post)

Model: interpretable phase curve.
- Default: HCM-based heuristic calibrated to Bangalore urban event patterns.
- Empirical override: if backend/data/phase_curve_empirical.json exists
  (generated by calibrate_phase_curve.py from Kaggle Bangalore Traffic Pulse
  dataset), those weights and thresholds are used instead.
"""

import json
from datetime import datetime, timedelta, timezone
from pathlib import Path
from typing import Dict, Any

# ---------------------------------------------------------------------------
# Phase curve — try to load empirical weights, fall back to HCM heuristic
# ---------------------------------------------------------------------------

_EMPIRICAL_PATH = Path(__file__).parent.parent / "data" / "phase_curve_empirical.json"
_SPATIAL_PATH = Path(__file__).parent.parent / "data" / "spatial_validation.json"

_CURVE_META = {
    "source": "heuristic",
    "description": "HCM-based heuristic calibrated to Bangalore urban event patterns",
    "dataset_rows": None,
    "event_day_rows": None,
}

# Default HCM-based phase curve
_PHASE_CURVE = {
    -2.0: 0.12,
    -1.0: 0.38,
    -0.5: 0.68,
     0.0: 1.00,
     0.5: 0.92,
     1.0: 0.80,
     2.0: 0.55,
     3.0: 0.28,
     4.0: 0.09,
}

_RISK_THRESHOLDS_DEFAULT = {"critical": 70, "high": 50, "medium": 28, "low": 0}
_RISK_THRESHOLDS = dict(_RISK_THRESHOLDS_DEFAULT)

# Spatial validation evidence (from police violation CSV)
_SPATIAL_VALIDATION = None
if _SPATIAL_PATH.exists():
    try:
        _SPATIAL_VALIDATION = json.loads(_SPATIAL_PATH.read_text())
    except Exception:
        pass

# Empirical override
if _EMPIRICAL_PATH.exists():
    try:
        _emp = json.loads(_EMPIRICAL_PATH.read_text())
        _raw_curve = _emp.get("phase_curve", {})
        if _raw_curve and len(_raw_curve) >= 6:
            _PHASE_CURVE = {float(k): float(v) for k, v in _raw_curve.items()}
            if _emp.get("risk_thresholds"):
                _RISK_THRESHOLDS = _emp["risk_thresholds"]
            _CURVE_META = {
                "source": "empirical",
                "description": _emp.get("calibration_notes", "Empirically derived from Bangalore Traffic Pulse dataset"),
                "dataset_rows": _emp.get("dataset_rows"),
                "event_day_rows": _emp.get("event_day_rows"),
                "tti_uplift_ratio": _emp.get("tti_uplift_ratio"),
            }
    except Exception:
        pass  # Keep heuristic on any parse error

RISK_THRESHOLDS = _RISK_THRESHOLDS

_ACTION_MAP = {
    "critical": {
        "color": "#ef4444",
        "action": "Immediate deployment — tow trucks + officers + barricades + active diversions",
        "manpower_multiplier": 1.5,
        "barricades": True,
        "diversions": True,
        "interval_mins": 10,
        "escalation": "Notify Traffic Control Room + Deputy Commissioner",
    },
    "high": {
        "color": "#f97316",
        "action": "Deploy patrol units + erect barricades + prepare diversion signs",
        "manpower_multiplier": 1.0,
        "barricades": True,
        "diversions": False,
        "interval_mins": 15,
        "escalation": "Notify Traffic Inspector",
    },
    "medium": {
        "color": "#eab308",
        "action": "Deploy monitoring team + standby barricades — escalate if congestion worsens",
        "manpower_multiplier": 0.6,
        "barricades": False,
        "diversions": False,
        "interval_mins": 30,
        "escalation": "Routine alert to beat officer",
    },
    "low": {
        "color": "#22c55e",
        "action": "Routine monitoring — no special deployment required",
        "manpower_multiplier": 0.25,
        "barricades": False,
        "diversions": False,
        "interval_mins": 60,
        "escalation": None,
    },
}

_HORIZON_LABELS = [
    ("Pre (-2h)",   -2.0),
    ("Pre (-1h)",   -1.0),
    ("Pre (-30m)",  -0.5),
    ("Event Start",  0.0),
    ("+1h",          1.0),
    ("+2h",          2.0),
    ("+3h",          3.0),
    ("Post (+4h)",   4.0),
]


def _interpolate(hours_from_start: float, duration_hours: float) -> float:
    """Interpolate phase factor from the curve, respecting event duration."""
    # Post-event: use linear dispersal from end of event
    if duration_hours > 0 and hours_from_start > duration_hours:
        hours_past_end = hours_from_start - duration_hours
        # At event end, factor ≈ 0.9 (crowd starts leaving); decays ~0.2/hour
        return max(0.0, 0.90 - 0.20 * hours_past_end)

    times = sorted(_PHASE_CURVE)
    if hours_from_start <= times[0]:
        return _PHASE_CURVE[times[0]]
    if hours_from_start >= times[-1]:
        return _PHASE_CURVE[times[-1]]

    for i in range(len(times) - 1):
        t0, t1 = times[i], times[i + 1]
        if t0 <= hours_from_start <= t1:
            frac = (hours_from_start - t0) / (t1 - t0)
            return _PHASE_CURVE[t0] + frac * (_PHASE_CURVE[t1] - _PHASE_CURVE[t0])
    return 0.0


def _risk_level(score: float) -> str:
    for level in ("critical", "high", "medium", "low"):
        if score >= RISK_THRESHOLDS[level]:
            return level
    return "low"


def _event_status(now: datetime, start: datetime, end) -> str:
    if end and now > end:
        return "concluded"
    if now >= start:
        return "active"
    hours_until = (start - now).total_seconds() / 3600
    if hours_until <= 1:
        return "imminent"
    if hours_until <= 24:
        return "upcoming"
    return "scheduled"


def generate_event_forecast(
    event,
    base_impact_score: float,
    base_manpower: int,
    base_barricades: int,
) -> Dict[str, Any]:
    """
    Generate a multi-horizon congestion forecast for an event.

    Parameters
    ----------
    event: ORM Event instance
    base_impact_score: predicted peak impact (0–100) from ImpactPrediction
    base_manpower: recommended officer count at peak
    base_barricades: recommended barricade count at peak
    """
    now = datetime.now(timezone.utc)

    start = event.start_time
    if start and start.tzinfo is None:
        start = start.replace(tzinfo=timezone.utc)

    end = event.end_time
    if end and end.tzinfo is None:
        end = end.replace(tzinfo=timezone.utc)

    duration_hours = (end - start).total_seconds() / 3600.0 if (end and start) else 2.0

    forecast_points = []
    for label, h_offset in _HORIZON_LABELS:
        phase = _interpolate(h_offset, duration_hours)
        risk_score = round(base_impact_score * phase, 1)
        level = _risk_level(risk_score)
        a = _ACTION_MAP[level]
        ts = (start + timedelta(hours=h_offset)) if start else None

        forecast_points.append({
            "label": label,
            "hours_from_start": h_offset,
            "timestamp": ts.isoformat() if ts else None,
            "risk_score": risk_score,
            "congestion_level": level,
            "color": a["color"],
            "recommended_action": a["action"],
            "manpower_required": max(1, round(base_manpower * a["manpower_multiplier"])),
            "barricades_count": max(0, round(base_barricades * a["manpower_multiplier"])),
            "barricades_required": a["barricades"],
            "diversions_required": a["diversions"],
            "monitoring_interval_mins": a["interval_mins"],
            "escalation": a["escalation"],
        })

    peak_point = max(forecast_points, key=lambda p: p["risk_score"])
    pre_deploy_point = next(
        (p for p in forecast_points if p["hours_from_start"] <= -1.0),
        forecast_points[0],
    )

    # Current moment interpolation
    now_offset = (now - start).total_seconds() / 3600.0 if start else 0.0
    current_phase = _interpolate(now_offset, duration_hours)
    current_score = round(base_impact_score * current_phase, 1)
    current_level = _risk_level(current_score)

    status = _event_status(now, start, end) if start else "scheduled"

    return {
        "event_id": str(event.id),
        "base_impact_score": round(base_impact_score, 1),
        "current_risk_score": current_score,
        "current_congestion_level": current_level,
        "current_action": _ACTION_MAP[current_level]["action"],
        "status": status,
        "forecast_points": forecast_points,
        "summary": {
            "peak_label": peak_point["label"],
            "peak_time": peak_point["timestamp"],
            "peak_risk_score": peak_point["risk_score"],
            "pre_deploy_by": pre_deploy_point["timestamp"],
            "total_impact_window_hours": round(duration_hours + 4, 1),
            "peak_manpower": peak_point["manpower_required"],
            "peak_barricades": peak_point["barricades_count"],
        },
        "model_provenance": {
            "curve_source": _CURVE_META["source"],
            "curve_description": _CURVE_META["description"],
            "event_day_rows": _CURVE_META.get("event_day_rows"),
            "spatial_validation": {
                "total_records": _SPATIAL_VALIDATION.get("total_violation_records") if _SPATIAL_VALIDATION else None,
                "max_uplift_ratio": _SPATIAL_VALIDATION.get("max_uplift_ratio") if _SPATIAL_VALIDATION else None,
                "finding": _SPATIAL_VALIDATION.get("finding") if _SPATIAL_VALIDATION else None,
            } if _SPATIAL_VALIDATION else None,
        },
    }
